---

- name: Check if WordPress database is already installed.
  become: no
  command: |
    wp \
    --path={{ wp_install_dir }} \
    --url={{ wp_domain }} \
    --admin_user={{ wp_admin_user }} \
    --admin_email={{ wp_admin_email }} \
    --title='{{ wp_site_title }}' \
    core install
