---

- name: Install site with `wp-cli`.
  become: no
  # The `--allow-root` flag is currently required by the
  # Docker driver tests, which run as `root`.  The default is
  # `false` so that WP-CLI will complain by default if someone
  # accidentally runs the role with `root` as the ansible user.
  command: |
    wp \
    --path={{ wp_install_dir }} \
    --url={{ wp_domain }} \
    --admin_user={{ wp_admin_user }} \
    --admin_password={{ wp_admin_password }} \
    --admin_email={{ wp_admin_email }} \
    --title='{{ wp_site_title }}' \
    {{ '--allow-root' if wp_cli_allow_as_root|default(false) else '' }} \
    core install

- name: Update default plugins with `wp-cli`.
  become: no
  # The `--allow-root` flag is currently required by the
  # Docker driver tests, which run as `root`.  The default is
  # `false` so that WP-CLI will complain by default if someone
  # accidentally runs the role with `root` as the ansible user.
  command: |
    wp \
    --path={{ wp_install_dir }} \
    {{ '--allow-root' if wp_cli_allow_as_root|default(false) else '' }} \
    plugin \
    update \
    --all
