---
wp_install_dir: "/home/vagrant/www"

php_enable_webserver: false
php_enablerepo: "remi,remi-php71"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ wp_domain }}"
    serveralias: "www.{{ wp_domain }}"
    documentroot: "{{ wp_install_dir }}"
    extra_parameters: |
          <FilesMatch \.php$>
            SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
          </FilesMatch>

mysql_enablerepo: "remi"
mysql_databases:
  - name: "{{ wp_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: "{{ wp_db_user }}"
    host: "%"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
